version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"        # Porta para conectar o RabbitMQ
      - "15672:15672"      # Porta para acessar o RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  rabbitmq_data:
    driver: local
